/*--------------------------------------------------------------
  Auto-generated Java code for class EaHusband

  Generated by QSEE-SuperLite multi-CASE, QSEE-Technologies Ltd
  www.qsee-technologies.com
----------------------------------------------------------------*/


public class EaHusband extends Man {

  //--------------------------------------------------------------
  // Attribute Declarations

  public java.util.Set wife;

  //--------------------------------------------------------------
  // Attributes implementing associations

  private java.util.Set ea_husband_to_eu_wife = new java.util.HashSet();


  //--------------------------------------------------------------
  // Accessor Methods

  /** accessor for 'wife' attribute
      @return value of wife  */
  public final java.util.Set getWife()   {
      return wife;
  }

  /** mutator for 'wife' attribute
      @param newValue The value to assign to wife  */
  public final void setWife (final java.util.Set newValue)    {
      wife = newValue;
  }


  //--------------------------------------------------------------
  // Accessor Methods implementing access to associated objects

  /** Gets the entire collection of 'EuWife' objects which are linked via the 'EaHusbandToEuWife' association
      @return Collection of 'EuWife' objects
  */
  public java.util.Set getEaHusbandToEuWife()   {
      return ea_husband_to_eu_wife;
  }

  /** Sets the entire collection of 'EuWife' objects which are linked via the 'EaHusbandToEuWife' association
      @param newObjects Collection of 'EuWife' objects to be associated with this instance
  */
  public void setEaHusbandToEuWife(java.util.Set newObjects)   {
      ea_husband_to_eu_wife = newObjects;
  }





}	// end of EaHusband class definition

