/*--------------------------------------------------------------
  Auto-generated Java code for class EuWife

  Generated by QSEE-SuperLite multi-CASE, QSEE-Technologies Ltd
  www.qsee-technologies.com
----------------------------------------------------------------*/


public class EuWife extends Man {

  //--------------------------------------------------------------
  // Attribute Declarations

  public EuHusband husband;

  //--------------------------------------------------------------
  // Attributes implementing associations

  private EuHusband eu_wife_to_eu_husband = null;
  private EaHusband eu_wife_to_ea_husband = null;


  //--------------------------------------------------------------
  // Accessor Methods

  /** accessor for 'husband' attribute
      @return value of husband  */
  public final EuHusband getHusband()   {
      return husband;
  }

  /** mutator for 'husband' attribute
      @param newValue The value to assign to husband  */
  public final void setHusband (final EuHusband newValue)    {
      husband = newValue;
  }


  //--------------------------------------------------------------
  // Accessor Methods implementing access to associated objects

  /** Gets the single 'EuHusband' object which is linked via the 'EuWifeToEuHusband' association
      @return A 'EuHusband' object (may be null if not set)
  */
  public EuHusband getEuWifeToEuHusband()   {
      return eu_wife_to_eu_husband;
  }

  /** Sets the single 'EuHusband' object which is linked via the 'EuWifeToEuHusband' association
      @param newObject The 'EuHusband' object to be associated with this instance
  */
  public void setEuWifeToEuHusband(EuHusband newObject)   {
      eu_wife_to_eu_husband = newObject;
  }


  /** Gets the single 'EaHusband' object which is linked via the 'EuWifeToEaHusband' association
      @return A 'EaHusband' object (may be null if not set)
  */
  public EaHusband getEuWifeToEaHusband()   {
      return eu_wife_to_ea_husband;
  }

  /** Sets the single 'EaHusband' object which is linked via the 'EuWifeToEaHusband' association
      @param newObject The 'EaHusband' object to be associated with this instance
  */
  public void setEuWifeToEaHusband(EaHusband newObject)   {
      eu_wife_to_ea_husband = newObject;
  }





}	// end of EuWife class definition

