/*--------------------------------------------------------------
  Auto-generated Java code for class Employee

  Generated by QSEE-SuperLite multi-CASE, QSEE-Technologies Ltd
  www.qsee-technologies.com
----------------------------------------------------------------*/


public class Employee extends Man {

  //--------------------------------------------------------------
  // Attribute Declarations

  public <null> profession;


  //--------------------------------------------------------------
  // Accessor Methods

  /** accessor for 'profession' attribute
      @return value of profession  */
  public final <null> getProfession()   {
      return profession;
  }

  /** mutator for 'profession' attribute
      @param newValue The value to assign to profession  */
  public final void setProfession (final <null> newValue)    {
      profession = newValue;
  }




}	// end of Employee class definition

