/*--------------------------------------------------------------
  Auto-generated Java code for class Man

  Generated by QSEE-SuperLite multi-CASE, QSEE-Technologies Ltd
  www.qsee-technologies.com
----------------------------------------------------------------*/


public class Man  {

  //--------------------------------------------------------------
  // Attribute Declarations

  public java.lang.String name;
  public java.lang.String surname;


  //--------------------------------------------------------------
  // Accessor Methods

  /** accessor for 'name' attribute
      @return value of name  */
  public final java.lang.String getName()   {
      return name;
  }

  /** mutator for 'name' attribute
      @param newValue The value to assign to name  */
  public final void setName (final java.lang.String newValue)    {
      name = newValue;
  }

  /** accessor for 'surname' attribute
      @return value of surname  */
  public final java.lang.String getSurname()   {
      return surname;
  }

  /** mutator for 'surname' attribute
      @param newValue The value to assign to surname  */
  public final void setSurname (final java.lang.String newValue)    {
      surname = newValue;
  }




}	// end of Man class definition

